[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = '0.8.20'
optimizer = true
optimizer_runs = 200

remappings = [
    "aave-v3-core/=lib/aave-v3-core/contracts/",
    "aave-v3-periphery/=lib/aave-v3-periphery/contracts/",
    "ds-test/=lib/forge-std/lib/ds-test/src/",
    "erc20-helpers/=lib/sparklend-advanced/lib/erc20-helpers/src/",
    "forge-std/=lib/forge-std/src/",
    "sparklend-advanced/=lib/sparklend-advanced/src/"
]

[fuzz]
runs = 1000

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
